apiVersion: apps/v1
kind: Deployment
metadata:
  name: cep-listhtml
  labels:
    app: cep
    k8s-app: cep-listhtml
    env: test
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: cep-listhtml
  template:
    metadata:
      annotations:
      labels:
        k8s-app: cep-listhtml
    spec:
      containers:
        - name: cep-listhtml
          image: rldourado/poc-actions02:list_html-v2-529ddb7
          imagePullPolicy: "Always"
          resources:
            requests:
              cpu: 250m
              memory: 256Mi
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
          envFrom:
            - configMapRef:
                name: cep
          ports:
            - name: flask
              containerPort: 5004
