apiVersion: v1
kind: Service
metadata:
  name: cep-keep
  labels:
    app: cep
    k8s-app: cep-keep
    env: test
spec:
  ports:
  - port: 5002
    protocol: TCP
    targetPort: 5002
  selector:
    k8s-app: cep-keep
  sessionAffinity: None
  type: ClusterIP
