apiVersion: v1
kind: Service
metadata:
  name: cep-listcsv
  labels:
    app: cep
    k8s-app: cep-listcsv
    env: test
spec:
  ports:
  - port: 5003
    protocol: TCP
    targetPort: 5003
  selector:
    k8s-app: cep-listcsv
  sessionAffinity: None
  type: ClusterIP
