apiVersion: v1
kind: Service
metadata:
  name: cep-listhtml
  labels:
    app: cep
    k8s-app: cep-listhtml
    env: test
spec:
  ports:
  - port: 5004
    protocol: TCP
    targetPort: 5004
  selector:
    k8s-app: cep-listhtml
  sessionAffinity: None
  type: ClusterIP
