apiVersion: v1
kind: Service
metadata:
  name: cep-main
  labels:
    app: cep
    k8s-app: cep-main
    env: test
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    k8s-app: cep-main
  sessionAffinity: None
  type: ClusterIP
